#! /usr/bin/env python
#  -*- coding: utf-8 -*-

""" About box for Lens Problem Designer """
#   (c)2019 Jeff Chamberlain
# This program is free software: you can use it under the terms of the
# GNU Affero General Public License version 3. This program is distributed
# WITHOUT ANY WARRANTY of any kind. See the GNU Affero General Public License
# for more details. <https://www.gnu.org/licenses/>.

# GUI generated by PAGE version 4.22


import tkinter as tk


def create_About(root):
    '''Starting point when module is imported by another program.'''
    global w
    w = tk.Toplevel(root)
    top = About(w)
    filename = "Fizzix137-32x32.gif"
    icon = tk.PhotoImage(file=filename)
    w.tk.call('wm', 'iconphoto', w._w, icon)
    w.iconify()
    w.update()
    w.deiconify()
    return (w, top)


class About:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("450x300+200+120")
        top.title("About Lens Problem Designer")
        top.configure(background="#0035d9")
        top.bind('<Button-1>', lambda e: click(e))

        self.About_label = tk.Label(top)
        self.About_label.place(x=75, y=40,  height=220, width=300)
        self.About_label.configure(background="#d9d9d9")
        self.About_label.configure(borderwidth="5")
        self.About_label.configure(foreground="#000000")
        self.About_label.configure(relief="raised")
        self.About_label.configure(text="Lens Problem Designer\n" +
                                   "\u00A92019 Jeff Chamberlain\n" +
                                   "Free Software License GNU AGPL 3\n" +
                                   "\nPython Source Code at:\n" +
                                   "https://github.com/fizzix137\n" +
                                   "\nClick to close.")


def click(event):
    w.withdraw()
